# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bot-crush

on:
  schedule:
    - cron:  '0 12 */1 * *'
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install chrome and chrome-driver
      run: |
        sudo apt-get install wget chromium-browser unzip -y
        wget https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/
        rm chromedriver_linux64.zip
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude app.py,messenger.py,.git,__pycache__,build,dist
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude app.py,messenger.py,.git,__pycache__,build,dist
        
      
            
    - name: Test getUserId and Send Message function
      env:
        ITEAMS_LOGIN : ${{ secrets.ITEAMS_LOGIN }}
        ITEAMS_PASS: ${{ secrets.ITEAMS_PASSWORD }}
      run: |
        cd ./CI-Test/
        python sendMsg-Test.py
                   

